from tkinter import *
from calculator_tkinter import *

root = Tk(className='Calculator')
root.resizable(FALSE,FALSE)

b1 = Button(root, text='1',font=20, height=1, width=3, borderwidth=3, command= button1)
root.bind(1, rb1)
b2 = Button(root, text='2', font=20, height=1, width=3, borderwidth=3, command=button2)
root.bind(2, rb2)
b3 = Button(root, text='3', font=20, height=1, width=3, borderwidth=3, command=button3)
root.bind(3, rb3)
b4 = Button(root, text='4', font=20, height=1, width=3, borderwidth=3, command=button4)
root.bind(4, rb4)
b5 = Button(root, text='5', font=20, height=1, width=3, borderwidth=3, command=button5)
root.bind(5, rb5)
b6 = Button(root, text='6', font=20, height=1, width=3, borderwidth=3, command=button6)
root.bind(6, rb6)
b7 = Button(root, text='7', font=20, height=1, width=3, borderwidth=3, command=button7)
root.bind(7, rb7)
b8 = Button(root, text='8', font=20, height=1, width=3, borderwidth=3, command=button8)
root.bind(8, rb8)
b9 = Button(root, text='9', font=20, height=1, width=3, borderwidth=3, command=button9)
root.bind(9, rb9)
b0 = Button(root, text='0', font=20, height=1, width=3, borderwidth=3, command=button0)
root.bind(0, rb0)
b_plus = Button(root, text='+', font=20, height=1, width=3, borderwidth=3, command=button_plus)
root.bind('<plus>', rb_plus)
b_minus = Button(root, text='-', font=20, height=1, width=3, borderwidth=3, command=button_minus)
root.bind('<minus>', rb_minus)
b_times = Button(root, text='*', font=20, height=1, width=3, borderwidth=3, command=button_times)
root.bind('<asterisk>', rb_times)
b_divide = Button(root, text='/', font=20, height=1, width=3, borderwidth=3, command=button_divide)
root.bind('<slash>', rb_devide)
b_equal = Button(root, text='=', font=20, height=1, width=3, borderwidth=3, command=button_equal)
root.bind('<equal>', rb_equal)
b_clear = Button(root, text='CLR', font=20, height=1, width=3, borderwidth=3, command=button_clear)
root.bind('<BackSpace>', rb_clear)


screen = Label(root,width=23, height=3, highlightthickness=2, highlightbackground='grey')

b1.grid(row=1, column=0)
b2.grid(row=1, column=1)
b3.grid(row=1, column=2)
b4.grid(row=2, column=0)
b5.grid(row=2, column=1)
b6.grid(row=2, column=2)
b7.grid(row=3, column=0)
b8.grid(row=3, column=1)
b9.grid(row=3, column=2)
b0.grid(row=4, column=1)
b_equal.grid(row=4, column=2)
b_plus.grid(row=1, column=3)
b_minus.grid(row=2, column=3)
b_times.grid(row=3, column=3)
b_divide.grid(row=4, column=3)
b_clear.grid(row=4, column=0)
screen.grid(row=0, columnspan=4, padx= 4, pady=4 )

root.mainloop()
